services:
  postgres:
    image: postgres:16
    container_name: battletanks-postgres
    environment:
      POSTGRES_USER: battletanks
      POSTGRES_PASSWORD: battletanks123
      POSTGRES_DB: battletanks_db
    ports:
      - "5433:5432"
    volumes:
      - battletanks_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: battletanks-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - battletanks_redis:/data

volumes:
  battletanks_pg:
  battletanks_redis: